// Generated by CoffeeScript 1.10.0
(function() {
  var PagerDuty, _expect, _object, _stripUndefined, request,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  request = require('request');

  _object = function(kvpairs) {
    var i, kv, len, res;
    res = {};
    for (i = 0, len = kvpairs.length; i < len; i++) {
      kv = kvpairs[i];
      res[kv[0]] = kv[1];
    }
    return res;
  };

  _stripUndefined = function(obj) {
    var k, v;
    return _object((function() {
      var results;
      results = [];
      for (k in obj) {
        v = obj[k];
        if (v !== void 0) {
          results.push([k, v]);
        }
      }
      return results;
    })());
  };

  _expect = function(expectedStatusCode, callback) {
    return function(err, response, body) {
      try {
        body = JSON.parse(body);
      } catch (undefined) {}
      if (err || response.statusCode !== expectedStatusCode) {
        return callback(err || (body && body.error ? new Error(body.error.errors[0]) : new Error('Unexpected HTTP code: ' + response.statusCode)));
      } else {
        return callback(null, body);
      }
    };
  };

  PagerDuty = (function() {
    module.exports = PagerDuty;

    function PagerDuty(arg) {
      this.serviceKey = arg.serviceKey, this.subdomain = arg.subdomain;
      if (this.serviceKey == null) {
        throw new Error('PagerDuty.constructor: Need serviceKey!');
      }
    }

    PagerDuty.prototype.create = function(arg) {
      var callback, description, details, incidentKey;
      description = arg.description, incidentKey = arg.incidentKey, details = arg.details, callback = arg.callback;
      if (description == null) {
        throw new Error('PagerDuty.create: Need description!');
      }
      return this._eventRequest(extend(arguments[0], {
        eventType: 'trigger'
      }));
    };

    PagerDuty.prototype.acknowledge = function(arg) {
      var callback, description, details, incidentKey;
      incidentKey = arg.incidentKey, details = arg.details, description = arg.description, callback = arg.callback;
      if (incidentKey == null) {
        throw new Error('PagerDuty.acknowledge: Need incidentKey!');
      }
      return this._eventRequest(extend(arguments[0], {
        eventType: 'acknowledge'
      }));
    };

    PagerDuty.prototype.resolve = function(arg) {
      var callback, description, details, incidentKey;
      incidentKey = arg.incidentKey, details = arg.details, description = arg.description, callback = arg.callback;
      if (incidentKey == null) {
        throw new Error('PagerDuty.resolve: Need incidentKey!');
      }
      return this._eventRequest(extend(arguments[0], {
        eventType: 'resolve'
      }));
    };

    PagerDuty.prototype._eventRequest = function(arg) {
      var callback, description, details, eventType, incidentKey, json;
      description = arg.description, incidentKey = arg.incidentKey, eventType = arg.eventType, details = arg.details, callback = arg.callback;
      if (eventType == null) {
        throw new Error('PagerDuty._request: Need eventType!');
      }
      details || (details = {});
      callback || (callback = function() {});
      json = {
        service_key: this.serviceKey,
        event_type: eventType,
        description: description,
        details: details,
        incident_key: incidentKey
      };
      return request({
        method: 'POST',
        uri: 'https://events.pagerduty.com/generic/2010-04-15/create_event.json',
        json: _stripUndefined(json)
      }, function(err, response, body) {
        if (err || response.statusCode !== 200) {
          return callback(err || new Error(body.errors[0]));
        } else {
          return callback(null, body);
        }
      });
    };

    PagerDuty.prototype.getEscalationPolicies = function(arg) {
      var callback, limit, offset, query;
      query = arg.query, offset = arg.offset, limit = arg.limit, callback = arg.callback;
      return this._getRequest({
        resource: 'escalation_policies',
        callback: callback,
        qs: {
          query: query,
          offset: offset,
          limit: limit
        }
      });
    };

    PagerDuty.prototype.getEscalationPoliciesOnCall = function(arg) {
      var callback, limit, offset, query;
      query = arg.query, offset = arg.offset, limit = arg.limit, callback = arg.callback;
      return this._getRequest({
        resource: 'escalation_policies/oncall',
        callback: callback,
        qs: {
          query: query,
          offset: offset,
          limit: limit
        }
      });
    };

    PagerDuty.prototype.createEscalationPolicy = function(arg) {
      var callback, escalationRules, name;
      name = arg.name, escalationRules = arg.escalationRules, callback = arg.callback;
      return this._postRequest({
        resource: 'escalation_policies',
        callback: callback,
        json: {
          name: name,
          escalation_rules: escalationRules
        }
      });
    };

    PagerDuty.prototype.getUsers = function(arg) {
      var callback, limit, offset, query;
      query = arg.query, offset = arg.offset, limit = arg.limit, callback = arg.callback;
      return this._getRequest({
        resource: 'users',
        callback: callback,
        qs: {
          query: query,
          offset: offset,
          limit: limit
        }
      });
    };

    PagerDuty.prototype.createUser = function(arg) {
      var callback, email, name, requesterId;
      name = arg.name, email = arg.email, requesterId = arg.requesterId, callback = arg.callback;
      return this._postRequest({
        resource: 'users',
        callback: callback,
        json: {
          name: name,
          email: email,
          requester_id: requesterId
        }
      });
    };

    PagerDuty.prototype.getServices = function(arg) {
      var callback, limit, offset, query;
      query = arg.query, offset = arg.offset, limit = arg.limit, callback = arg.callback;
      return this._getRequest({
        resource: 'services',
        callback: callback,
        qs: {
          query: query,
          offset: offset,
          limit: limit
        }
      });
    };

    PagerDuty.prototype.createService = function(arg) {
      var callback, escalationPolicyId, name, serviceKey, type;
      name = arg.name, escalationPolicyId = arg.escalationPolicyId, type = arg.type, serviceKey = arg.serviceKey, callback = arg.callback;
      return this._postRequest({
        resource: 'services',
        callback: callback,
        json: {
          service: {
            name: name,
            escalation_policy_id: escalationPolicyId,
            type: type,
            service_key: serviceKey
          }
        }
      });
    };

    PagerDuty.prototype._getRequest = function(arg) {
      var callback, limit, offset, qs, resource, uri;
      resource = arg.resource, qs = arg.qs, offset = arg.offset, limit = arg.limit, callback = arg.callback;
      callback || (callback = function() {});
      uri = 'https://' + this.subdomain + '.pagerduty.com/api/v1/' + resource;
      return request({
        method: 'GET',
        uri: uri,
        qs: _stripUndefined(qs),
        headers: {
          'Authorization': 'Token token=' + this.serviceKey
        }
      }, _expect(200, callback));
    };

    PagerDuty.prototype._postRequest = function(arg) {
      var callback, json, resource, uri;
      resource = arg.resource, json = arg.json, callback = arg.callback;
      callback || (callback = function() {});
      uri = 'https://' + this.subdomain + '.pagerduty.com/api/v1/' + resource;
      return request({
        method: 'POST',
        uri: uri,
        json: _stripUndefined(json),
        headers: {
          'Authorization': 'Token token=' + this.serviceKey
        }
      }, _expect(201, callback));
    };

    return PagerDuty;

  })();

}).call(this);
